FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# blockapp-streamcircle

Stream Circle/Hybrid block-streamcircle API.

## Access token [/Account/Login]

### Login [POST]

Get API access tokens

+ Request (application/json)

        {
          "Username": "streamcircle@hybrid.com",
          "Password": "XYuSZ64p5lIL1o"
        }

+ Response 200 (application/json)

        {  
           "Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IldXYTVBM1FJV1JxVS1nWTVLRzJQR",
           "SCtoken": "OiJSUzI1NiIsIng1dCI6IlIxSnR4Z3B4OHJnV3BXZWR3UGZQS1VQODhYdy",
           "UserHash": "10035"
        }

## Release access tokens [/Account/Logout]

### Logout [POST]

+ Request (application/json)
    + Headers

            Authorization: OiJSUzI1NiIsIng1dCI6IlIxSnR4Z3B4OHJnV3BXZWR3UGZQS1VQODhYdy
            PortalAuthorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IldXYTVBM1FJV1JxVS1nWTVLRzJQR

+ Response 200 (application/json)