FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# blockapp-streamcircle

Stream Circle/Hybrid block-streamcircle API.

## Access token [/api/Account/Login]

### Login [POST]

Get API access tokens

+ Request (application/json)

   + Body
   
            {
              "Username": "streamcircle@hybrid.com",
              "Password": "XYuSZ64p5lIL1o"
            }

+ Response 200 (application/json)

    + Attributes
    
            + Token: (string) - Authorization token
            + SCtoken: (string) - PortalAuthorization token
            + UserHash: (number) - User internal ID

   + Body
   
            {  
                "Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IldXYTVBM1FJV1JxVS1nWTVLRzJQR",
                "SCtoken": "OiJSUzI1NiIsIng1dCI6IlIxSnR4Z3B4OHJnV3BXZWR3UGZQS1VQODhYdy",
                "UserHash": "10035"
            }

## Release access tokens [/api/Account/Logout]

### Logout [POST]

+ Request (application/json)
    + Headers

            Authorization: OiJSUzI1NiIsIng1dCI6IlIxSnR4Z3B4OHJnV3BXZWR3UGZQS1VQODhYdy
            PortalAuthorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IldXYTVBM1FJV1JxVS1nWTVLRzJQR

+ Response 200 (application/json)

## Block Import [/pba/api/v2/schedpattern/import]

Plan/Block import

### Import [POST]

+ Request (application/json)
    + Headers

            Authorization: OiJSUzI1NiIsIng1dCI6IlIxSnR4Z3B4OHJnV3BXZWR3UGZQS1VQODhYdy
            PortalAuthorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IldXYTVBM1FJV1JxVS1nWTVLRzJQR
    
   + Body
   
            {
              "Server": "CHANNEL_NAME",
              "Name": "AdBlock name",
              "Description": "Hybrid adblock data",
              "Block": "True",
              "BlockUID": "AD456987_UID",
              "Items": [
                {
                  "StartTime": "00:00:00.000",
                  "Duration": "000:15.000",
                  "Description": "Cars 3 (clip description)",
                  "TemplateName": "INTERSTITIALCLIP_default",
                  "FileName": "/ProvysMedia/STANDARD/Trailers/cars-3-part-1.mp4",
                  "TemplateParams": [
                    {
                      "Name": "VIDEOPORT",
                      "Value": "@port1"
                    },
                    {
                      "Name": "VIDEOOFFSET",
                      "Value": "0"
                    }
                  ],
                  "Tags": [
                    {
                      "Name": "clip"
                    }
                  ]
                },
                {
                  "StartTime": "00:00:15.000",
                  "Duration": "001:00.000",
                  "Description": "Big buck bunny",
                  "TemplateName": "INTERSTITIALCLIP_default",
                  "FileName": "/ProvysMedia/STANDARD/Trailers/big_buck_bunny.mp4",
                  "FileOriginalPath": "http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4",
                  "FileIngestWorkflowNM": "DOWNLOAD",
                  "TemplateParams": [
                    {
                      "Name": "VIDEOPORT",
                      "Value": "@port1"
                    },
                    {
                      "Name": "VIDEOOFFSET",
                      "Value": "0"
                    }
                  ],
                  "Tags": [
                    {
                      "Name": "clip"
                    }
                  ]
                }
              ]
            }

+ Response 200 (application/json)

        {
          "Result": true,
          "Message": "Plan imported successfully",
        }
        
## Graphical templates [/pba/api/v2/template/list]

### List [GET]

List of installed graphical templates

+ Request (application/json)
    + Headers

            Authorization: OiJSUzI1NiIsIng1dCI6IlIxSnR4Z3B4OHJnV3BXZWR3UGZQS1VQODhYdy
            PortalAuthorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IldXYTVBM1FJV1JxVS1nWTVLRzJQR

+ Response 200 (application/json)

            {
              "Items": [
                {
                  "Kind": "T",
                  "Name": "INTERSTITIALCLIP_default",
                  "Description": "Interstitial clip",
                  "Note": "Video clip without the secondary full-screen logo.",
                  "TemplateParams": [
                    {
                      "Name": "VIDEOFILENAME",
                      "Label": "Clip"
                    },
                    {
                      "Name": "VIDEONAME",
                      "Label": "Video ID"
                    },
                    {
                      "Name": "VIDEOPORT",
                      "Label": "Videoserver port",
                      "Value": "@port1",
                      "Type": "E",
                      "Format": "@port1;@port2"
                    },
                    {
                      "Name": "VIDEOOFFSET",
                      "Label": "Play from",
                      "Value": "0"
                    },
                    {
                      "Name": "FILENAME",
                      "Label": "File"
                    },
                    {
                      "Name": "DURATION",
                      "Label": "Duration",
                      "Type": "T"
                    }
                  ]
                },
                {
                  "Kind": "S",
                  "Name": "CRAWLINGTEXT_default",
                  "Description": "Crawling text",
                  "Note": "Crawling text with an image as secondary event. Adjustable font, colour, crawling speed and spacing of instances of the text.",
                  "TemplateParams": [
                    {
                      "Name": "TEXT",
                      "Label": "Crawling text",
                      "Value": "Crawling text"
                    },
                    {
                      "Name": "FONTNAME",
                      "Label": "Font",
                      "Value": "Arial"
                    },
                    {
                      "Name": "TEXTCOLOR",
                      "Label": "Text colour",
                      "Value": "0 0 0"
                    },
                    {
                      "Name": "PANELCOLOR",
                      "Label": "Panel colour",
                      "Value": "1 1 1"
                    },
                    {
                      "Name": "SPEED",
                      "Label": "Crawling speed",
                      "Value": "-0.2"
                    },
                    {
                      "Name": "SPACING",
                      "Label": "Instances spacing",
                      "Value": "2400"
                    }
                  ]
                },
                {
                  "Kind": "S",
                  "Name": "SCROLLINGTEXT_default",
                  "Description": "Scrolling text",
                  "Note": "Scrolling text with an image as secondary event. Adjustable font, colour and hold-off time of the text.",
                  "TemplateParams": [
                    {
                      "Name": "TEXT",
                      "Label": "Scrolling text",
                      "Value": "Scrolling text"
                    },
                    {
                      "Name": "FONTNAME",
                      "Label": "Font",
                      "Value": "Arial"
                    },
                    {
                      "Name": "TEXTCOLOR",
                      "Label": "Text colour",
                      "Value": "0 0 0"
                    },
                    {
                      "Name": "PANELCOLOR",
                      "Label": "Panel colour",
                      "Value": "1 1 1"
                    },
                    {
                      "Name": "HOLDOFF",
                      "Label": "Hold-off time (ms)",
                      "Value": "3000",
                      "Type": "T"
                    }
                  ]
                },
                {
                  "Kind": "T",
                  "Name": "WEATHERCLIP_default",
                  "Description": "Weather clip",
                  "Note": "Weather announcement break with the secondary full-screen logo. Weather data periodically read from an RSS-feed by means of a job. Select a background image and an audio or a video file to be playing along (if a video is chosen, only its audio track(s) will be used).",
                  "TemplateParams": [
                    {
                      "Name": "AUDIOFILENAME",
                      "Label": "Background audio"
                    },
                    {
                      "Name": "AUDIONAME",
                      "Label": "Media ID"
                    },
                    {
                      "Name": "PORT",
                      "Label": "Videoserver port",
                      "Value": "@port2"
                    },
                    {
                      "Name": "OFFSET",
                      "Label": "Play from",
                      "Value": "0"
                    },
                    {
                      "Name": "BACKGROUND",
                      "Label": "Background image",
                      "Value": "/ProvysMedia/STANDARD/Images/WeatherBackground.jpg"
                    }
                  ]
                }
              ]
            }     
            
## Folder content [/pba/api/v2/folder/export]

### Export [GET]

+ Request (application/json)
    + Headers

            Authorization: OiJSUzI1NiIsIng1dCI6IlIxSnR4Z3B4OHJnV3BXZWR3UGZQS1VQODhYdy
            PortalAuthorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IldXYTVBM1FJV1JxVS1nWTVLRzJQR

    + Body
    
            {
                "Path": "/ProvysMedia/STANDARD/Trailers"
            }

+ Response 200 (application/json)

            {
              "Folders": [
                {
                  "SymbolicName": "Trailers",
                  "SymbolicFullpath": "/ProvysMedia/STANDARD/Trailers",
                  "IngestWorkflowNM": "DOWNLOAD",
                  "Files": [
                    {
                      "UniqueID": "88cb6b93-ad2b-4c22-8cc9-0f0235679780",
                      "UMID": "big_buck_bunny.mp4",
                      "SymbolicName": "big_buck_bunny.mp4",
                      "OriginalPath": "http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4",
                      "LiveFeed": false,
                      "IsPlanControlled": false,
                      "Mime": "video/mp4",
                      "VideoFormat": "AVC/AAC LC",
                      "Bitrate": "613147",
                      "Resolution": "8",
                      "Duration": "001:00.095",
                      "Size": 5510872,
                      "LastWriteTime": "2017-08-28 13:04:56",
                      "Audios": [
                        {
                          "Frequency": "22.05 KHz",
                          "BitRate": "64000",
                          "Language": "English",
                          "Channels": "2",
                          "Positions": "Front: L R",
                          "Format": "AAC LC"
                        }
                      ],
                      "Tags": [],
                      "Segments": []
                    },
                    {
                      "UniqueID": "cac060be-74f4-4134-a06f-17ad3caddd23",
                      "UMID": "cars-3-part-1.mp4",
                      "SymbolicName": "cars-3-part-1.mp4",
                      "LiveFeed": false,
                      "IsPlanControlled": false,
                      "Mime": "video/mp4",
                      "VideoFormat": "AVC/AAC LC",
                      "Bitrate": "9473843",
                      "Resolution": "8",
                      "Duration": "000:35.368",
                      "Size": 42466636,
                      "LastWriteTime": "2017-01-20 11:34:11",
                      "Audios": [
                        {
                          "Frequency": "44.1 KHz",
                          "BitRate": "128000",
                          "Language": "English",
                          "Channels": "2",
                          "Positions": "Front: L R",
                          "Format": "AAC LC"
                        }
                      ],
                      "Tags": [
                        {
                          "Name": "default"
                        }
                      ],
                      "Segments": []
                    },
                    {
                      "UniqueID": "fbe8968c-e58b-4a19-abc6-c3317e8e37f7",
                      "UMID": "cars-3-part-2.mp4",
                      "SymbolicName": "cars-3-part-2.mp4",
                      "LiveFeed": false,
                      "IsPlanControlled": false,
                      "Mime": "video/mp4",
                      "VideoFormat": "AVC/AAC LC",
                      "Bitrate": "9579023",
                      "Resolution": "8",
                      "Duration": "000:51.383",
                      "Size": 62357229,
                      "LastWriteTime": "2017-01-20 11:34:16",
                      "Audios": [
                        {
                          "Frequency": "44.1 KHz",
                          "BitRate": "128000",
                          "Language": "English",
                          "Channels": "2",
                          "Positions": "Front: L R",
                          "Format": "AAC LC"
                        }
                      ],
                      "Tags": [
                        {
                          "Name": "default"
                        }
                      ],
                      "Segments": []
                    },
                    {
                      "UniqueID": "ae75dab8-7af3-4c7c-8fd9-f1b271234772",
                      "UMID": "halo.halo.1x01.padelana.madonna.dvb.xvid.multidub-bb.avi",
                      "SymbolicName": "halo.halo.1x01.padelana.madonna.dvb.xvid.multidub-bb.avi",
                      "LiveFeed": false,
                      "IsPlanControlled": false,
                      "Mime": "video/x-msvideo",
                      "VideoFormat": "XVID/MPA1L3",
                      "Bitrate": "967517",
                      "Resolution": "8",
                      "Duration": "028:52.680",
                      "Size": 244279296,
                      "LastWriteTime": "2006-04-06 05:49:40",
                      "Audios": [
                        {
                          "Frequency": "48.0 KHz",
                          "BitRate": "85000",
                          "Channels": "1",
                          "Format": "MPA1L3"
                        },
                        {
                          "Frequency": "48.0 KHz",
                          "BitRate": "56559",
                          "Channels": "1",
                          "Format": "MPA1L3"
                        }
                      ],
                      "Tags": [],
                      "Segments": []
                    },
                    {
                      "UniqueID": "230b2a38-5b14-4109-920c-70d6925b5986",
                      "UMID": "sleepless-part-1.mp4",
                      "SymbolicName": "sleepless-part-1.mp4",
                      "LiveFeed": false,
                      "IsPlanControlled": false,
                      "Mime": "video/mp4",
                      "VideoFormat": "AVC/AAC LC",
                      "Bitrate": "8712299",
                      "Resolution": "8",
                      "Duration": "001:07.067",
                      "Size": 74142846,
                      "LastWriteTime": "2017-01-20 11:34:21",
                      "Audios": [
                        {
                          "Frequency": "44.1 KHz",
                          "BitRate": "128000",
                          "Language": "English",
                          "Channels": "2",
                          "Positions": "Front: L R",
                          "Format": "AAC LC"
                        }
                      ],
                      "Tags": [
                        {
                          "Name": "default"
                        }
                      ],
                      "Segments": []
                    }
                  ],
                  "FilesCount": 5
                }
              ]
            }